-- vim.pack.del({
--     { src = "https://github.com/nvim-telescope/telescope.nvim" },
--     { src = "https://github.com/nvim-telescope/telescope-fzf-native.nvim" },
--     { src = "https://github.com/nvim-lua/plenary.nvim" },
-- })
--
